accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"


urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

jin_tonic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView, ProjectUpdateView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ProjectUpdateView.as_view(), name='update'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">


{% include 'head.html' %}


<body style="font-family: 'NanumSquareRoundR';">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>


    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class ="jintonic_footer">

    <div class="jintonic_footer_button">
        <span>Since 2019.10.31</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="jintonic_logo">By JIN_TONIC For Sol</h6>
    </div>

</div>

templates/head.html
{% load static %}

<head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title> Jin_tonic </title>

<!--        Bootstrap link-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

<!--        Google Fonts Link-->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

<!--        Google Material ICONs-->
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

<!--        Default CSS Link-->
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

        <style>
            @font-face{
                font-family: 'NanumSquareRoundR';
                src: local('NanumSquareRoundR'),
                url("{% static 'font/NanumSquareRoundR.ttf' %}") format("opentype");
            }
        </style>

</head>

templates/header.html
    <div class = "jintonic_header ">
        <div>
            <h1 class = "jintonic_logo" >
                <a href="{% url 'articleapp:list' %}" class="jintonic_header_nav">
                    Kyum&Sol
                </a>
            </h1>
        </div>
        <div class="jintonic_header_navbar">
            <a href="{% url 'articleapp:list' %}" class="jintonic_header_nav">
                <span>Memories</span>
            </a>
            <a href="{% url 'projectapp:list' %}" class="jintonic_header_nav">
                <span>Moments</span>
            </a>

            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:create' %}?next={{ request.path }}" class="jintonic_header_nav">
                <span>Sign Up</span>
            </a>
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="jintonic_header_nav">
                <span>Sign In</span>
            </a>
            {% else %}
            <a href="{% url 'subscribeapp:list' %}" class="jintonic_header_nav">
                <span>Album</span>
            </a>
            <a href="{% url 'accountapp:detail' pk=user.pk %}" class="jintonic_header_nav">
                <span>My Page</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="jintonic_header_nav">
                <span>Sign Out</span>
            </a>
            {% endif %}
        </div>
    </div>